const details = [
    {
        Name: 'Prof. Dr. S.M. Mahbub Ul Haque Majumder',
        Title: 'Dean',
        Age: 70,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 100000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/ba2349468906ab10fb616570af90f7da.jpg',
    },
    {
        Name: 'Professor Dr. Md. Fokhray Hossain',
        Title: 'Associate Dean & Professor',
        Age: 68,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 90000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/b520b602c379adcac0e08070ed19cae3.png',
    },
    {
        Name: 'Professor Dr. Touhid Bhuiyan',
        Title: 'Professor & Head',
        Age: 65,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 80000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/4383d374442e6e72ad12a0bb79c36aab.JPG',
    },
    {
        Name: 'Dr. Bibhuti Roy',
        Title: 'Visiting Professor',
        Age: 60,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 75000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/8e89c862b7e4ab4f1ad6d34f1118de38.png',
    },
    {
        Name: 'Dr. Neil Perez Balba',
        Title: 'Visiting Professor',
        Age: 55,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 75000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/11cc8af4166117abe65e937afdf62610.png',
    },
    {
        Name: 'Dr. S.R.Subramanya',
        Title: 'Visiting Professor',
        Age: 66,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 75000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/1b752e73e676d3bc9a78fe722a83db28.png',
    },
    {
        Name: 'Dr. Sheak Rashed Haider Noori',
        Title: 'Associate Professor and Associate Head',
        Age: 55,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 60000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/a9db387ba2a795b09f880a0f1392d8f3.JPG',
    },
    {
        Name: 'Md Zahid Hasan',
        Title: 'Assistant Professor & Coordinator MIS',
        Age: 50,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 60000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/ba2349468906ab10fb616570af90f7da.jpg',
    },
    {
        Name: 'Mr. Md. Sadekur Rahman',
        Title: 'Assistant Professor',
        Age: 50,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 60000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/b04632cba44f0c60bdb45411c3873c33.JPG',
    },
    {
        Name: 'Mr. Shah Md Tanvir Siddiquee',
        Title: 'Assistant Professor',
        Age: 50,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 60000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/14ad363ef4b867aff377c274b1e1834c.JPG',
    },
    {
        Name: 'Nusrat Jahan',
        Title: 'Lecturer',
        Age: 35,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 40000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/090a68ca2b33d952a2a6a4c543790df6.gif',
    },
    {
        Name: 'Mr. Md. Firoz Hasan',
        Title: 'Lecturer',
        Age: 38,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 40000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/eace384be552db7bca6ae46a62d713c7.png',
    },
    {
        Name: 'Ms. Itisha Nowrin',
        Title: 'Lecturer',
        Age: 35,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 40000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/e38f4154f2a1b1210a040ff27c56c6af.png',
    },
    {
        Name: 'Mst. Eshita Khatun',
        Title: 'Lecturer',
        Age: 35,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 35000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/41b86b69ba4f581e7b10c46ec7793090.gif',
    },
    {
        Name: 'Ms. Tapasy Rabeya',
        Title: 'Lecturer',
        Age: 30,
        Faculty: 'Faculty of Science and Information Technology',
        Salary: 35000,
        img: 'https://faculty.daffodilvarsity.edu.bd/images/teacher/07da42372034fcf309ab43e4e3cd4a25.gif',
    },
]
    
    
    
    